language: node_js
node_js:
  - "4"
  - "stable"
notifications:
  email: false
cache:
  directories:
    - $HOME/.npm/
    - node_modules
matrix:
  include:
    - node_js: "4"
      script: npm run coverage
      before_install:
        - npm install -g codecov
      after_success:
        - codecov
